### ISSUE TITLE
Forum Discussion of Issues encountered in KSP 1.12

### ISSUE THREAD

**Issue by Growflavor** [KSP-RO/RSSTimeFormatter#17]
we much appreciate the continued work & updates...here is a fyi since we do not know where to discuss issues we encounter:

I installed RSS via CKAN for KSP 1.12.2 & have encountered the same issues. If of any help, I am happy to try any beta versions for 1.12 when development gets to that point.

https://forum.kerbalspaceprogram.com/index.php?/topic/139335-ksp-113-rss-datetime-formatter-v10/&do=findComment&comment=3995837

KSP forum user Pehvbot: "with 1.12 and Real Solar System and it looks like the current build of RSSDateTime throws a bunch of Reflection errors."

KSP forum user BIOZ: "Same here. I'm unable to enter the VAB/SPH"

Thanks!

**Comment by jwvanderbeck** [comment]
This mod is not yet updated to 1.12 and most likely something changed in the methods it hooks in game

**Comment by PiezPiedPy** [comment]
The Unity version has been changed so the project needs to be rebuilt using the new game engine dll's 😉

**Comment by jwvanderbeck** [comment]
Again, this mod is not released for KSP 1.12.

**Comment by PiezPiedPy** [comment]
@jwvanderbeck I know ?? I said This mod needs to be rebuilt using the new Unity Engine DLL's also apparently a minor change to the PrintDateDeltaCompact method

**Comment by jwvanderbeck** [comment]
WHEN we release for 1.12 it will yes.  That is not happening right now.

**Comment by PiezPiedPy** [comment]
@jwvanderbeck ALRIGHT - KEEP YOUR NICKERS ON 😬

**Comment by PiezPiedPy** [comment]
Unofficial release for KSP1.12.x here [GitHub RSSDateTime-v1.10.2.0 KSP 1.12.x Unofficial.zip](https://github.com/PiezPiedPy/RSSTimeFormatter/releases/tag/v1.10.2)

**Comment by jwvanderbeck** [comment]
This mod is part of the KSP-RO suite of mods.  When KSP-RO moves to KSP 1.12, this mod will be updated.  Until then, this is supported on 1.10 only.  While I can't stop you from forking and doing releases of your own, it seems both pointless (as the rest of the suite isn't 1.12) and kind of rude.

So let me just emphasize this here, This mod is not supported on 1.12, neither is the rest of KSP-RO.  Other than that, do what you want.

**Comment by PiezPiedPy** [comment]
@jwvanderbeck I took your response "WHEN we release for 1.12 it will yes. That is not happening right now." as rude tbh but...
Trajectories is not dependant on RSS but a lot of people use both mods. Due to your response I took it upon myself to fix the issue as I knew what the problem was and pointed out so.

As for your last post I think you may have an anger issue and should maybe take a walk in the park for example.
You do realize these projects are open source and subject to abuse by people like me who think they can do what they want but at least you gave me permission after the fact and I thank you for that. 

Have a nice day.
